name: Lint And Run Tests

on: [push]

jobs:
  lint-job:
    runs-on: ubuntu-slim
    steps:
      - name: Check Out Code
        uses: actions/checkout@v6.0.2
      - name: Install And Set Up UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.14
      - run: uv sync --no-dev
            
